### PR TITLE
Corrections to README.md

### PR DESCRIPTION
**Pull request by haxorjim**
Found a few things in the readme that weren't working. Thanks for the library!

### CODE REVIEW

**Comment by haxorjim** [comment]
> did you manage to run the order_book example? if yes, i think that needs updating in the README

No, I haven't used that feature myself.

**Comment by danpaquin** [comment]
We do not need to add www. on my end, but either way this line should be updated since the URL should not have "settings" in it anymore.  Instead, "profile".

**Comment by haxorjim** [comment]
> We do not need to add [www](http://www). on my end, but either way this line should be updated since the URL should not have "settings" in it anymore. Instead, "profile".

Done

**Comment by mcardillo55** [comment]
Thank you!

**Pull request merged**
