### PR TITLE
Fix closed connections bug

### PR DESCRIPTION
**Pull request by deanblacc**
The `while` loop in `_listen` isn't doing what you think it is. 

Calling `recv()` blocks the thread. If no messages are received the connection is closed and a `WebSocketConnectionClosedException` is thrown.  

At this point, we should attempt a reconnection using the parameters previously set.

Sidenote: The conditional on a line ~77 is breaking the entire class. Theres already a PR (#262 ) for this so I didn't make those changes.. however this commit allows us to circumvent that error also

### CODE REVIEW

**Comment by danpaquin** [comment]
This is simple, yet effective.  Thanks!

**Comment by danpaquin** [comment]
This makes sense, but we had a more serious bug when we didn't include the ping.  Reconnecting on every pong doesn't seem too elegant, so how might be have best of both worlds?

**Comment by deanblacc** [comment]
hey @danpaquin can you link the ping issue/bug youre referring to ? Would like to take a look.

**Comment by danpaquin** [comment]
This has been fixed via #337 

Thanks!

**Pull request closed without merging**
