### PR TITLE
Added a simple level2 orderbook implemention

### PR DESCRIPTION
**Pull request by lirenz**
Completely experimental & looking to solicit feedback. This can be updated to extend WebSocketClient (like the current setup if necessary).

Basically, I log all messages into files. I prefer an orderbook that isn't tied to the WebSocketClient since I can replay logged messages with this orderbook.

### CODE REVIEW

**Comment by danpaquin** [comment]
If possible, I would like to avoid making a new class for each channel.  I will leave this open for discussion, but I believe the Websocket class is setup to digest all the different channel types and there's no way we can create a method that works for everyone's implementation.

**Comment by lirenz** [comment]
Right - this doesn't create a new class for the channel. OrderBookL2 is just a class that digests message data from a websocket to organize the book (which is the class).

**Comment by danpaquin** [comment]
Yes, that's a nice idea.  I will merge this request when all channel types have been accounted for.

**Comment by lirenz** [comment]
btw - what do you mean by "all channel types"?

**Comment by danpaquin** [comment]
Hello @lirenz -- similar to the level2 scope, GDAX allows multiple channels to be opened via the websocket.  Rather than implementing each channel on its own, I would rather approach all of them in once client (if possible) and setup the nuances of each channel within __init__.

Documentation Reference:
https://docs.gdax.com/#channels

Thanks for your support!
Dan

**Comment by furryboffin** [comment]
Hi, did you guys merge this level2 order book in the end? That would be really useful.
Anything I can do to help, just let me know

**Comment by danpaquin** [comment]
To prevent duplicate code, this should be implemented as an inherited order book, rather than it's own object.  I hope you understand, but I appreciate your contribution.

**Pull request closed without merging**
