### PR TITLE
Development

### PR DESCRIPTION
**Pull request by brokencog**
get_product_trades() was incorrectly setting default value of limit argument to string '', rather than int 0.

### CODE REVIEW

**Comment by brokencog** [comment]
Sorry for the slow response.

The issue seemed fairly simple -- the function get_product_trades() has several arguements, one of which is "limit".  This arg was being assigned a default value of '' ... that is: limit='' ... this is causing a problem in the function when limit is used as an integer.  I was attempting to change the function definition to "limit=0" ... however I suck at git (and don't really care to unsuck) and as a result don't know what has been pushed or pulled for review.

**Comment by alimcmaster1** [comment]
Ive fixed this in #311

**Comment by brokencog** [comment]
Great.

-daniel

**Comment by danpaquin** [comment]
This is fantastic.  I merged the changes.  Thank you all for your contribution on this.

**Pull request merged**
